version: '3.8'

networks:
  chatroom:

services:
  myapp:
    build:
      context: .
      dockerfile: app.dockerfile
    container_name: chatroom
#    restart: always
    networks:
      - chatroom
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: chatroom
      ROCKETMQ_NAMESRV_ADDR: rocketmq-namesrv:9876
    ports:
      - "80:80"



